move to release of rust-analyzer
- replace git repo and compilation of rust-analyzer with release
  as the compiled one was much slower than the release
  and had some extra debug output, which interrupted editign

diff --git a/rust-analyzer/Makefile b/rust-analyzer/Makefile
--- a/rust-analyzer/Makefile
+++ b/rust-analyzer/Makefile
@@ -12,15 +12,18 @@ include ../helpers.mk
 PREFIX ?= $(HOME)/.cargo/
 SHELL ?= /bin/bash
 
+# NB: using release as previous compilations were stuck in debug mode, which is much slower
+_release_tar_url := https://github.com/rust-lang/rust-analyzer/releases/download/2026-09-21/rust-analyzer-x86_64-unknown-linux-gnu.gz
+_release_tar := $(notdir $(_release_tar_url))
+_release = $(basename $(_release_tar))
+_release_sig := b2d24ce2bda2ea05b1ad7c2917d205f8111775f703ccd908e6061803ae8257d0
 
-_url := https://github.com/rust-lang/rust-analyzer.git
-_branch := release
-_src := rust-analyzer
 _install := $(PREFIX)/bin/rust-analyzer
+_bin := rust-analyzer
 
 
 .PHONY: all
-all: git-hash
+all: $(_bin)
 
 
 .PHONY: install
@@ -29,28 +32,35 @@ install: $(_install)
 
 .PHONY: uninstall
 uninstall:
-	if [ -f "$(_src)/Makefile" ]; then $(MAKE) -ik -C $(_src) PREFIX=$(PREFIX) uninstall; fi
+	rm -f $(_install)
 
 
 .PHONY: clean
 clean:
 	$(call log_info,clean $(_src))
-	if [ -f "$(_src)/Makefile" ]; then $(MAKE) -ik -C $(_src) clean; fi
+	rm -f $(_release_tar)
+	rm -f $(_bin)
 
 
 .PHONY: download
-download:
-	@# creates or updates repo at $(_src)
-	$(call git_clone_fetch_reset,$(_url),$(_src),$(_branch))
+download: $(_release_tar)
 
 
-git-hash: download
-	@# git-hash is updated when the local repo commit is changed
-	$(call check_commit, $(_src))
-
-
-$(_install): git-hash
+$(_release_tar):
 	$(call log_info,updating $@...)
-	cd $(_src) && \
-	which rustc || . $(HOME)/.cargo/env && \
-		cargo xtask install --server
+	@# using wget, downloading with curl resulted in bad checksums
+	wget -c $(_release_tar_url)
+	echo "$(_release_sig) $(_release_tar)" | sha256sum --check --status \
+		|| (echo "checksum failed: $(_release_tar)"; rm $(_release_tar); exit 1)
+
+
+$(_bin): $(_release_tar)
+	$(call log_info,updating $@...)
+	gunzip -c $(_release_tar) > $@ \
+	&& chmod +x $@
+
+
+$(_install): $(_bin)
+	$(call log_info,updating $@...)
+	cp $^ $@ \
+	&& chmod +x $@
